### ISSUE TITLE
Outdated gc_auth_custom_users.csv format does not throw specific error

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy_gated_content#59]
One of our site owners attempted to upload their gc_auth_custom_users.csv with what I *think* is a very old column layout:
"Id,Firstname,Lastname,YBillingMember,Email"
...instead of the expected:
"Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site".

The file looked like it imported on her end with no validation error thrown.

Can this validation get added to the roadmap?

**Comment by hamrant** [comment]
Hi @TomScarboroughYMCA 

I think this is bad idea to add validation for CSV file, because migration can be different for each project, you just need to add customization for `migrate_plus.migration.gc_auth_custom_users.yml` config.

So in your case you just need to fix fields:

```yml
  fields:
    -
      name: member_id
      label: 'ID'
    -
      name: first_name
      label: 'Firstname'
    -
      name: last_name
      label: 'Lastname'
    -
      name: member
      label: 'YBillingMember'
    -
      name: email
      label: 'Email'
```

If you want to use Lastname in user name, just add this value to `source`:

```yml
  name:
    plugin: concat
    source:
      - first_name
      - last_name
      - member_id
```

cc @podarok
